- name: Forti Facts
  hosts: fortigateslab
  gather_facts: no
  connection: httpapi
  # ansible.builtin.debug:
  #   var: ansible_facts
  collections:
    - fortinet.fortios
    # - fortinet.fortios.fortios_facts
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
#    wan_interface: {{ wan }}
    vdom: "root"
  tasks:
    - name: gather system interface
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        selector: system_interface
      register: interfaces
    - name: Save interfaces to cache
      set_fact:
        export_fg_interfaces: "{{ interfaces }}"
        cacheable: yes
    - name: Combine results
      combine_results:
        prev_result: interfaces

    # - debug:
    #     msg: "{{results}}"
    # debug:
    # msg: "{{ ansible_facts }}"

    - name: Copy ansible facts to a file.
      copy:
        content: "{{ interfaces }}"
        dest: /tmp/ansible_facts_details.json
